# Generated by Django 3.2.9 on 2021-11-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUjiKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kendaraan', models.CharField(max_length=200)),
                ('nama_pemilik', models.CharField(max_length=200)),
                ('lulus', models.BooleanField()),
                ('tanggal_pemeriksaan', models.DateField(auto_now=True)),
                ('no_chasis', models.BooleanField(default=True)),
                ('pelat_pabrik_pembuat', models.BooleanField(default=True)),
            ],
        ),
    ]
