# Generated by Django 3.2.9 on 2021-11-19 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211119_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataujikendaraan',
            name='bantalan_roda',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataujikendaraan',
            name='pegas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataujikendaraan',
            name='pemasangan_sumbu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataujikendaraan',
            name='sumbu',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataujikendaraan',
            name='suspensi_roda_belakang',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataujikendaraan',
            name='suspensi_roda_depan',
            field=models.BooleanField(default=True),
        ),
    ]
