# Generated by Django 3.2.9 on 2021-11-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211119_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataujikendaraan',
            name='keadaan_ban',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataujikendaraan',
            name='keadaan_pelek',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataujikendaraan',
            name='kedalaman_kembang_ban',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataujikendaraan',
            name='penguasaan_ban_or_pelek',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataujikendaraan',
            name='ukuran_dan_jenis_ban',
            field=models.BooleanField(default=True),
        ),
    ]
