# Generated by Django 3.2.9 on 2021-11-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211119_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataujikendaraan',
            name='sistem_bahan_bakar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dataujikendaraan',
            name='sistem_kelistrikan',
            field=models.BooleanField(default=True),
        ),
    ]
