# Generated by Django 3.2.9 on 2021-11-21 12:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211119_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataujikendaraan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataujikendaraan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='dataujikendaraan',
            name='tanggal_pemeriksaan',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
