# Generated by Django 3.2.9 on 2021-11-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20211121_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataujikendaraan',
            name='bukti_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='dataujikendaraan',
            name='kendaraan_image',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
