# Generated by Django 3.2.9 on 2021-11-21 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20211121_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataujikendaraan',
            old_name='lamput_mundur',
            new_name='lampu_mundur',
        ),
    ]
