# Generated by Django 3.2.9 on 2021-11-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_lamput_mundur_dataujikendaraan_lampu_mundur'),
    ]

    operations = [
    ]
