# Generated by Django 3.2.9 on 2021-11-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211121_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataujikendaraan',
            name='srgb_efisiensi_rem',
            field=models.BooleanField(default=True),
        ),
    ]
