# Generated by Django 3.2.9 on 2021-11-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_dataujikendaraan_kendaraan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataujikendaraan',
            name='user_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
