# Generated by Django 3.2.9 on 2021-11-23 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_dataujikendaraan_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataujikendaraan',
            name='user_token',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
